---
- name: Gathering service facts.
  service_facts:
  register: services_state

- name: Allow SkyWalking service ports.
  firewalld:
    port: '{{ item.value }}/tcp'
    zone: 'public'
    permanent: 'yes'
    immediate: 'true'
    state: 'enabled'
  loop: '{{ skywalking_port_arg | dict2items }}'
  when:
    - services_state.ansible_facts.services["firewalld.service"] is defined
    - services_state.ansible_facts.services["firewalld.service"].state == 'running'
