---
- name: Add the group skywalking.
  group:
    name: '{{ skywalking_arg.user }}'

- name: Add the user skywalking.
  user:
    name: '{{ skywalking_arg.user }}'
    comment: '{{ skywalking_arg.user }}'
    group: '{{ skywalking_arg.user }}'
    home: '{{ skywalking_path }}/skywalking'

- name: Install Apache SkyWalking.
  unarchive:
    src: '{{ skywalking_soft_url }}/apache/skywalking/{{ skywalking_version }}/apache-skywalking-apm-es7-{{ skywalking_version }}.tar.gz'
    dest: '{{ skywalking_path }}/skywalking'
    owner: '{{ skywalking_arg.user }}'
    group: '{{ skywalking_arg.user }}'
    mode: '0750'
    exclude: '{{ skywalking_exclusions }}'
    extra_opts: [--strip-components=1]
    remote_src: 'yes'
    validate_certs: 'no'
  register: skywalking_update
  until: skywalking_update is succeeded
  retries: 3
  delay: 2
