---
- name: Sets ElasticSearch node variables for Cluster.
  set_fact:
    skywalking_elastic_hosts: '{{ elastic_servers }}'
  when:
    - skywalking_elastic_dept | bool

- name: Sets ZooKeeper node variables for Cluster.
  set_fact:
    skywalking_zoo_servers: '{{ zoo_servers }}'
  when:
    - skywalking_zoo_dept | bool

- name: Include tasks for specific OS.
  include: '{{ ansible_os_family }}.yml'

- name: Include firewall tasks.
  include: 'firewall.yml'

- name: Include installation tasks.
  include: 'install.yml'

- name: Include configuration tasks.
  include: 'configureation.yml'

- name: Reload the SkyWalking initialize service.
  shell: echo ''
  notify: 'Ensure SkyWalking service is enabled'
  when:
    - skywalking_servers[0] in ansible_default_ipv4.address
    - skywalking_update is changed or skywalking_config_update is changed or skywalking_systemd_update is changed

- name: Force the handler to run immediately.
  meta: flush_handlers

- name: Reload the SkyWalking member service.
  shell: echo ''
  notify: 'Ensure SkyWalking service is enabled'
  when:
    - skywalking_servers[0] not in ansible_default_ipv4.address
    - skywalking_update is changed or skywalking_config_update is changed or skywalking_systemd_update is changed