---
- name: Enable SkyWalking service.
  systemd:
    name: '{{ item }}'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  loop:
    - 'skywalking-oap.service'
    - 'skywalking-webapp.service'
  listen: Ensure SkyWalking service is enabled